apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecotrack-demo
  namespace: ecotrack-dev
  labels:
    app: ecotrack-demo
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecotrack-demo
      version: v1
  template:
    metadata:
      labels:
        app: ecotrack-demo
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: ecotrack-demo
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: html-content
        configMap:
          name: ecotrack-demo-html